---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: demo
  namespace: monitoring
spec:
  version: v2.25.0
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-operated
      port: web
  serviceMonitorSelector:
    matchLabels:
      team: devops-bootcamp
  ruleSelector:
    matchLabels:
      team: devops-bootcamp
  serviceAccountName: prometheus
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  enableAdminAPI: false
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 20Gi
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  replicas: 1
  retention: 7d
  scrapeInterval: 30s
